export type Version = {
    version: 9
};

/**
 * Represents any type of message that can appear in a conversation.
 */
export type MessagePart = SystemMessagePart | UserMessagePart | AssistantMessagePart | ToolMessagePart;

/**
 * System prompt message.
 * IMPORTANT: The system prompt can only be set via {@link Profile.systemPrompt}.
 */
export type SystemMessagePart = {
    role: 'system';
    content: string;
};

/**
 * Represents any message generated by the assistant.
 * Can either be plain text or a tool call.
 */
export type AssistantMessagePart = AssistantTextMessagePart | AssistantToolCallMessagePart;

/**
 * Message from the user.
 */
export type UserMessagePart = {
    role: 'user';
    content: {
        type: 'text';
        text: string;
    };
};

/**
 * Message from the assistant that contains plain text content.
 */
export type AssistantTextMessagePart = {
    role: 'assistant';
    content: {
        type: 'text';
        text: string;
    };
};

/**
 * Message from the assistant that contains a tool call.
 */
export type AssistantToolCallMessagePart = {
    role: 'assistant';
    content: {
        type: 'tool-call';
        toolCall: ToolCall;
    };
};

/**
 * Message part representing a tool's response to the assistant's tool call.
 */
export type ToolMessagePart = {
    role: 'tool';
    toolResult: ToolResult;
    toolCall: ToolCall;
};

/**
 * Defines a tool invocation request.
 */
export type ToolCall = {
    id?: string;
    toolName: string;
    params?: Record<string, any>;
};

/**
 * Defines the result of a tool invocation.
 */
export type ToolResult = {
    id?: string;
    toolName: string;
    isError: boolean;
    output: string;
};

/**
 * Data models that represent what a model can send back
 * as part of a response to a `getCompletion` / `getCompletionStream` request.
 */
type TextResponsePart = {
    /**
     * Plain text output from the model.
     */
    type: 'text';
    text: string;
};

type ToolCallsResponsePart = {
    /**
     * Tool calls returned by the model.
     */
    type: 'tool-calls';
    toolCalls: ToolCall[];
};

type UsageResponsePart = {
    /**
     * Information about token usage returned by the provider.
     */
    type: 'usage-stats';
    usageStats: UsageStats;
};

export type CompletionStreamResponsePart = TextResponsePart | ToolCallsResponsePart | UsageResponsePart;

/**
 * What a model sends back as response to a `getCompletion` request.
 */
export type CompletionResponse = (TextResponsePart | ToolCallsResponsePart) & {
    usageStats?: UsageStats;
};

export type Embedding = number[];

export type EmbeddingResponse = {
    embeddings: Embedding[];
};

export type UsageStats = {
    /**
     * Total input tokens (cached and uncached).
     */
    inputTokens: number;
    outputTokens: number;
    cacheReadTokens?: number;
    cacheWriteTokens?: number;
};

export type Options = {
    [k: string]: any;
};

export type DynamicModelConfig = {
    provider: string;
    providerOptions?: Options | ((abortSignal?: AbortSignal) => Promise<Options>);
    models: string | string[] | ((abortSignal?: AbortSignal) => Promise<string[]>);
    modelOptions?: Options | ((abortSignal?: AbortSignal) => Promise<Options>);
    modelInfo?: ModelInfo | ((abortSignal?: AbortSignal) => Promise<ModelInfo>);
};

export type LanguageModelInfo = {
    type: 'language';

    /**
     * Models's maximum context window (in number of tokens).
     */
    maximumContextWindow: number;

    /**
     * Information about model usage costs (in $ per million tokens).
     */
    cost?: {
        inputTokens: number;
        outputTokens: number;
        cacheRead: number;
        cacheWrite: number;
    };
};

export type EmbeddingModelInfo = {
    type: 'embedding';

    /**
     * Model's maximum input size (in number of tokens).
     */
    maxInputSize?: number;

    /**
     * The number of dimensions (elements) in the output embedding vector generated by the model.
     */
    outputSize?: number;
};

export type ModelInfo = LanguageModelInfo | EmbeddingModelInfo;

export type DefaultModelConfig = Omit<DynamicModelConfig, 'provider'>;

export type ModelConfig = {
    provider: string;
    providerOptions?: Options;
    model: string;
    modelOptions?: Options;
    modelInfo?: ModelInfo;
};

export type ModelsConfig = {
    configs: DynamicModelConfig[] | (() => Promise<DynamicModelConfig[]>);
} & Version;

export type LanguageModel = {

    /**
     * Represents the model config used to create this concrete model.
     */
    config: ModelConfig;

    /**
     * Returns the next model reply in a sequence of messages.
     *
     * @param messageParts a list of alternating user / assistant messages.
     * @param tools a list of tools the model can use to retrieve additional information.
     * @param abortSignal a signal object that will be used to abort this operation.
     * @returns the model's reply, with optional token usage stats.
     */
    getCompletion: (messageParts: MessagePart[], tools?: Tool[], abortSignal?: AbortSignal) => Promise<CompletionResponse>;

    /**
     * Returns the next model reply in a sequence of messages, as a stream of text / tool calls parts.
     *
     * @param messageParts a list of alternating user / assistant messages.
     * @param tools a list of tools the model can use to retrieve additional information.
     * @param abortSignal a signal object that will be used to abort this operation.
     * @returns an async iterable that will be iterated to retrieve each part of the model's reply.
     */
    getCompletionStream: (messageParts: MessagePart[], tools?: Tool[], abortSignal?: AbortSignal) => Promise<AsyncIterable<CompletionStreamResponsePart>>;
};

export type EmbeddingModel = {

    /**
     * Represents the model config used to create this concrete model.
     */
    config: ModelConfig;

    /**
     * Returns the embeddings generated for a list of input text chunks.
     *
     * @param chunks list of strings to embed.
     * @param abortSignal a signal object that will be used to abort this operation.
     * @returns an EmbeddingResponse representing the model's reply, or null if the model failed to reply.
     */
    getEmbedding: (chunks: string[], abortSignal?: AbortSignal) => Promise<EmbeddingResponse>;
};

export type Model = LanguageModel | EmbeddingModel;

export type ModelFactory = {

    /**
     * Represents the canonical name or id of this model factory (provider / connector).
     *
     * IMPORTANT: Using a name that is already registered by existing user-defined or built-in model factories, will overwrite those factories with this implementation.
     */
    provider: string;

    /**
     * Used when no user-defined model config exists (ex. models.[json|jsonc|js|ts] file).
     *
     * @param abortSignal a signal object that will be used to abort this operation.
     * @returns a list of dynamic model configs.
     */
    getDefaultModelConfigs: (abortSignal?: AbortSignal) => Promise<DefaultModelConfig[]>;

    /**
     * Used when user-defined or default model configs contain wildcard patterns in the model names.
     * The models returned by this method will be matched against those patterns.
     *
     * @param providerOptions an object containing user-defined or default provider options (ex. apiKey).
     * @param abortSignal a signal object that will be used to abort this operation.
     * @returns a list of model names.
     */
    getAvailableModels?: (providerOptions: Options, abortSignal?: AbortSignal) => Promise<string[]>;

    /**
     * @param config a model config containing the model name, model options, provider options and optional model info.
     * @param abortSignal a signal object that will be used to abort this operation.
     * @returns a model implementation that will be used for completions.
     */
    getModel: (config: ModelConfig, abortSignal?: AbortSignal) => Promise<Model>;

} & Version;

/**
 * A profile groups together a set of tools, a system prompt and a models selection strategy.
 * It represents a "persona" that can be used by any session.
 */
export type Profile = {
    /**
     * Represents the canonical name or id of this profile.
     *
     * IMPORTANT: Using a name that is already registered by existing user-defined or built-in profiles,
     * will overwrite those profiles with this implementation.
     */
    name: string;

    /**
     * A human-readable string which is rendered in the UI.
     */
    description?: string;

    /**
     * A collection of tool identifiers that are *exposed* to the model when this profile is active.
     *
     * The value can be:
     *   * a single glob string,
     *   * an array of glob strings,
     *   * or an asynchronous function that resolves to either of the above.
     *
     * Glob syntax ('*' and '?') is supported.
     */
    toolSet: string | string[] | ((abortSignal?: AbortSignal) => Promise<string[]>);

    /**
     * System‑level instructions that are sent to the model once at the start of a session.
     * If omitted, the model receives no explicit system prompt.
     */
    systemPrompt?: string | ((modelConfig: ModelConfig, abortSignal?: AbortSignal) => Promise<string>);

    /**
     * Used to filter the available model configs and return only those that should be used with this profile.
     * The first model will be used and the rest will be used as fallback in specific scenarios.
     */
    useModels?: ((availableModelConfigs: ModelConfig[], abortSignal?: AbortSignal) => Promise<ModelConfig[]>);
} & Version;

export type SessionBlueprintBase = {
    /**
     * Represents the canonical name or id of this blueprint.
     *
     * IMPORTANT: Using a name that is already registered by existing user-defined or built-in blueprints, will overwrite those blueprints with this implementation.
     */
    name: string;

    /**
     * A human-readable string which is rendered in the UI.
     */
    description?: string;

    /**
     * Represents the functionality which uses the blueprint. Used to differentiate the blueprint type.
     */
    target: string;

    /**
     * The canonical name or id of the used profile. If the specified profile is not found, a default one will be used.
     */
    profile: string;
} & Version;

export type ChatSessionBlueprint = SessionBlueprintBase & {
    target: 'chat';

    /**
     * A list of alternating user / assistant message parts used to initiate the conversation
     * when starting a new chat session using this blueprint.
     *
     * IMPORTANT: The last message part should be a user message part.
     */

    messages: MessagePart[] | ((modelConfig: ModelConfig, abortSignal?: AbortSignal) => Promise<MessagePart[]>);
};

export type ProblemAutocorrectArgs = ProblemInfo & {
    /**
     * Additional information about the previous problem auto-correct attempt which failed.
     */
    previousAttemptInfo?: ProblemAutocorrectPreviousAttemptInfo;
};

/**
 * Provides information about a previous attempt to correct a problem.
 */
export type ProblemAutocorrectPreviousAttemptInfo = {
    /**
     * The response generated by the model when attempting the auto-correct.
     */
    modelResponse: string;

    /**
     * An error message describing why the auto-correct attempt failed.
     */
    errorMessage: string;
};

export type ProblemAutocorrectSessionBlueprint = SessionBlueprintBase & {
    target: 'problem-autocorrect';

    /**
    * A list of alternating user / assistant message parts used to initiate the conversation
    * when starting a new problem auto-correct session using this blueprint.
    *
    * IMPORTANT: The last message part should be a user message part.
    */
    messages: ((args: ProblemAutocorrectArgs, modelConfig: ModelConfig, abortSignal?: AbortSignal) => Promise<MessagePart[]>);

    /**
     * A list of patterns to match against the problem message.
     * This list is used to identify which problems can be solved by this blueprint.
     */
    problemMessagePatterns: string[];

    /**
     * Function used to parse the model's response and identify file edits to be performed.
     */
    processModelResponse: (response: string, abortSignal?: AbortSignal) => Promise<FileEdit[]>;
};

export type ProblemExplainArgs = ProblemInfo;

export type ProblemExplainSessionBlueprint = SessionBlueprintBase & {
    target: 'problem-explain';

    /**
     * A list of alternating user / assistant message parts used to initiate the conversation
     * when starting a new problem explain session using this blueprint.
     *
     * IMPORTANT: The last message part should be a user message part.
     */
    messages: (args: ProblemExplainArgs, modelConfig: ModelConfig, abortSignal?: AbortSignal) => Promise<MessagePart[]>;
};

export type GenerateCommitMessageSessionBlueprint = SessionBlueprintBase & {
    target: "git-source-control";

    /**
     * A list of alternating user / assistant message parts used to initiate the conversation
     * when starting a new summarize-changes session using this blueprint.
     *
     * IMPORTANT: The last message part should be a user message part.
     */
    messages: MessagePart[] | ((modelConfig: ModelConfig, abortSignal?: AbortSignal) => Promise<MessagePart[]>);
};

export type SpecadorLivePreviewType =
    'module' | 'parameter' | 'port' | 'variable' | 'always-block' | 'fsm-transition' |
    'interface' | 'modport' |
    'test' | 'class' | 'field' | 'function' | 'task' | 'typedef' | 'constraint' | 'assert' |
    'entity' | 'generic' |
    'unit' | 'subtype' | 'check';

export type SpecadorLivePreviewArgs = {
    /**
     * Type of the element which is currently under preview.
     */
    elementKind: SpecadorLivePreviewType;

    /**
     * Name of the element which is currently under preview.
     */
    elementName: string;

    /**
     * File of the element which is currently under preview.
     */
    filename: string;

    /**
     * Content of the existing comment, used for enhancing.
     */
    existingComment: string;
};

export type SpecadorLivePreviewSessionBlueprint = SessionBlueprintBase & {
    target: 'specador-live-preview';

    /**
     * A list of alternating user / assistant message parts used to initiate the conversation
     * when starting a new session using this blueprint.
     *
     * IMPORTANT: The last message part should be a user message part.
     */
    messages: ((args: SpecadorLivePreviewArgs, modelConfig: ModelConfig, abortSignal?: AbortSignal) => Promise<MessagePart[]>);
};

export type VerissimoParameterInfo = {
    /**
     * Name of the Verissimo linting rule parameter.
     */
    name: string;

    /**
     * Description of the Verissimo linting rule parameter.
     */
    description: string;

    /**
     * Value given by the user to the Verissimo linting rule parameter.
     */
    value: string;
};

export type VerissimoCheckInfo = {
    /**
     * Title of the Verissimo linting rule.
     */
    title: string;

    /**
     * Description of the Verissimo linting rule.
     */
    description: string;

    /**
     * List of parameters associated to the Verissimo linting rule.
     */
    parametersInfo: VerissimoParameterInfo[];

    /**
     * Additional examples of correct code snippets for which the linting rule passes.
     */
    allowedExamples?: string[];

    /**
     * Additional examples of incorrect code snippets for which the linting rule fails.
     */
    notAllowedExamples?: string[];
};

export type VerissimoFailureInfo = ProblemInfo & {
    /**
     * The severity level of the Verissimo failure.
     */
    severity: 'error' | 'warning' | 'info' | 'disabled';
};

export type VerissimoFailureAdditionalInformation = {
    /**
     * The entire content of the Verissimo failure file.
     */
    fileContent: string;
};

export type VerissimoFailureAutocorrectArgs = {
    /**
     * A list of Verissimo failure information, associated with each failure the blueprint will fix.
     */
    failuresInfo: VerissimoFailureInfo[];

    /**
     * Information about the Verissimo linting rule.
     */
    checkInfo: VerissimoCheckInfo;

    /**
     * Additional information about the Verissimo failures.
     */
    additionalInformation: VerissimoFailureAdditionalInformation;

    /**
     * Errors which occurred during the previous Verissimo Auto-correct session, which failed, partially or entirely.
     */
    previousAttemptInfos?: ProblemAutocorrectPreviousAttemptInfo[];
};

/**
 * Provides information about a previous attempt to correct one Verissimo failure.
 */
export type VerissimoFailureAutocorrectPreviousAttemptInfo = ProblemAutocorrectPreviousAttemptInfo & {
    /**
     * Each failed Verissimo Auto-correct failure information is associated to at least one Verissimo failure.
     * In the case of other error types, which cannot be associated to one Verissimo failure, the array will be empty.
     */
    associatedFailuresIndex: number[];
};

export type VerissimoFailureAutocorrectSessionBlueprint = SessionBlueprintBase & {
    target: 'verissimo-autocorrect';

    /**
     * A list of alternating user / assistant messages used to initiate the conversation
     * when starting a new session using this blueprint.
     *
     * IMPORTANT: The last message should be a user message.
     */
    messages: ((args: VerissimoFailureAutocorrectArgs, modelConfig: ModelConfig, abortSignal?: AbortSignal) => Promise<MessagePart[]>);

    /**
     * A list of Verissimo rule names to match against the linting failure.
     * This list is used to identify which verissimo linting failures can be solved by this blueprint.
     * 'ALL' will match against all Verissimo rules.
     * @deprecated This field is deprecated. Instead of specifying rule names in the blueprint, associate the blueprint name to a category/rule in the Verissimo ruleset XML file.
     */
    ruleNames: string[];

    /**
     * Function used to parse the model's response and identify file edits to be performed and encountered errors.
     * @returns a tuple consisting of both file edits successfully parsed from the model's response, and
     *     a list of information regarding erroneously generated responses. This information is useful for
     *     future Verissimo Auto-Correct sessions, to give an accurate response.
     */
    processModelResponse: (response: string) => Promise<{ fileEdits: VerissimoFileEdit[], erroneousEditInfos: VerissimoFailureAutocorrectPreviousAttemptInfo[] }>;
};

export type VerissimoFailureExplainArgs = {
    /**
     * A list of verissimo failure information, associated with each failure the blueprint will fix.
     */
    failureInfo: VerissimoFailureInfo;

    /**
     * Information about the Verissimo linting rule.
     */
    checkInfo: VerissimoCheckInfo;

    /**
     * Additional information about the verissimo failure.
     */
    additionalInformation: VerissimoFailureAdditionalInformation;
};

export type VerissimoFailureExplainSessionBlueprint = SessionBlueprintBase & {
    target: 'verissimo-failure-explain';

    /**
     * A list of alternating user / assistant messages used to initiate the conversation
     * when starting a new session using this blueprint.
     *
     * IMPORTANT: The last message should be a user message.
     */
    messages: (args: VerissimoFailureExplainArgs, modelConfig: ModelConfig, abortSignal?: AbortSignal) => Promise<MessagePart[]>;
};

/**
 * Represents a file edit for a verissimo problem that replaces a specific
 * range of lines in a file with new content.
 */
export type VerissimoFileEdit = FileEdit & {
    /**
     * A list of verissimo problem indexes which are solved
     * by this file edit.
     */
    solvedProblemsIndex: number[];
};

/**
 * Represents a detected problem in source code, including location,
 * surrounding context, and severity.
 */
export type ProblemInfo = {
    /**
     * A human-readable description of the problem.
     */
    message: string;

    /**
     * The path of the file containing the problem.
     * Can be absolute or relative to the project root.
     */
    filePath: string;

    /**
     * The starting line (1-based) where the problem occurs.
     */
    startLine: number;

    /**
     * The ending line (1-based) where the problem occurs.
     */
    endLine: number;

    /**
     * A snippet of code including the problematic section,
     * with 3 lines of context above and below.
     */
    surroundingCode: string;

    /**
     * The severity level of the problem.
     */
    severity: 'error' | 'warning';
};

/**
 * Represents a code edit that replaces a specific range of lines
 * in a file with new content.
 */
export type FileEdit = {
    /**
     * The path of the file to be edited.
     * Can be absolute or relative to the project root.
     */
    filePath: string;

    /**
     * The starting line (1-based, inclusive) of the section to be replaced.
     */
    startLine: number;

    /**
     * The ending line (1-based, inclusive) of the section to be replaced.
     */
    endLine: number;

    /**
     * The replacement code.
     */
    code: string;
};

export type CodeCompletionSessionBlueprint = SessionBlueprintBase & {
    target: 'code-completion';

    /**
     * Used to process the model's reply before using it as a code completion.
     * @param reply a string with the model's reply.
     * @returns a list of strings representing the code completions extracted from the model's reply.
     */
    processModelResponse?: (reply: string, abortSignal?: AbortSignal) => Promise<string[]>;

    messages: MessagePart[] | ((modelConfig: ModelConfig, abortSignal?: AbortSignal) => Promise<MessagePart[]>);
};

export type PromptArgs = {
    [name: string]: number | string;
};

export type PromptSnippet = {

    /**
     * Represents the canonical name or id of this snippet.
     *
     * IMPORTANT: Using a name that is already registered by existing user-defined or built-in snippets, will overwrite those snippets with this implementation.
     */
    name: string;

    description?: string;

    /** Signature used to refer to this snippet in the prompt.
      *
      * Example: \@design hierarchy | expand up <up_levels:number> | expand down <down_levels:number>
      */
    signature: string;

    /**
     * Whether to expand snippets and symbols nested in the prompt string.
     */
    expand?: boolean;

    /**
     * Use to define the snippet expansion.
     */
    prompt: string | ((args: PromptArgs, modelConfig?: ModelConfig, abortSignal?: AbortSignal) => Promise<string>);

} & Version;

/**
 * Represents the base information for a tool.
 */
export type ToolBase = {
    /**
     * Unique identifier for the tool.
     */
    name: string;

    /**
     * Human-readable name for the tool (displayed in UI).
     */
    displayName: string;

    /**
     * Human-readable description of what the tool does.
     */
    description: string;

    /**
     * JSON Schema defining the expected input structure for the tool.
     * Useful for validating input before invoking the tool.
     */
    inputSchema?: JSONSchema;

    /**
     * Indicates whether user confirmation is required before invoking the tool.
     */
    needsConfirmation: boolean;

    /**
     * Message shown to the user when confirmation is needed.
     * Example: "This tool will edit 'file.sv'. Do you want to continue?"
     */
    confirmationMessage: string;
};

/**
 * Represents a tool that can be invoked.
 */
export type Tool = ToolBase & {
    /**
     * Function to invoke the tool.
     * @param arg input data for the tool (validated against inputSchema).
     * @param abortSignal optional AbortSignal to cancel the tool's execution.
     * @returns the tool result.
     */
    invoke: (arg: any, abortSignal?: AbortSignal) => Promise<string>;
};

/**
 * Defines a JSON Schema for validating tool inputs.
 * Supports basic types and nested structures.
 */
export type JSONSchema = {
    /**
     * Type of the value.
     */
    type: "string" | "number" | "boolean" | "object" | "array";

    /**
     * Properties of an object (if type is "object").
     * Each property has its own JSONSchema.
     */
    properties?: Record<string, JSONSchema>;

    /**
     * Schema of array items (if type is "array").
     */
    items?: JSONSchema;

    /**
     * List of required property names (if type is "object").
     */
    required?: string[];

    /**
     * Allowed enum values for the property.
     */
    enum?: (string | number | boolean)[];

    /**
     * Description of the property.
     */
    description?: string;
};

/**
 * Information about a file that contains instructions & rules for an agent
 * (e.g. an `AGENTS.md` file).
 */
export type RuleFile = {
    /**
     * Path to the rule file (e.g. "<project_path>/AGENTS.md").
     */
    filePath: string;

    /**
     * Marks the file as the root/primary rule file.
     */
    isRootFile: boolean;

    /**
     * The file's contents - defined only when `isRootFile` is true.
     */
    content?: string;
};

/**
 * Represents the platform the runtime is executing on.
 */
export type Platform =
    | "aix"
    | "darwin"
    | "freebsd"
    | "haiku"
    | "linux"
    | "openbsd"
    | "sunos"
    | "win32"
    | "cygwin"
    | "netbsd";

/**
 * Options for executing a shell command via api.runtime.exec.
 */
export type ExecOptions = {
    /**
     * Working directory for the command execution.
     */
    cwd?: string;

    /**
     * Environment variables to pass to the command.
     */
    env?: Record<string, string>;

    /**
     * Timeout for the command execution in milliseconds. Defaults to 5000 (5 seconds).
     */
    timeout?: number;

    /**
     * Maximum output buffer size in bytes. Defaults to 1MB.
     */
    maxOutputSize?: number;
};

/**
 * Result of a shell command execution via api.runtime.exec.
 */
export type ExecResult = {
    /**
     * The standard output of the command.
     */
    stdout: string;

    /**
     * The standard error output of the command.
     */
    stderr: string;

    /**
     * The exit code of the command.
     */
    exitCode: number;

    /**
     * Whether the command timed out.
     */
    timedOut: boolean;
};

export type InputDocument = {
    /**
     * A unique id generated from the document's content.
     */
    documentId: string;

    /**
     * The absolute path to the input document.
     */
    filePath: string;

    /**
     * The file format of the input document.
     */
    format: string;
};

export type ConvertedDocument = {
    /**
     * A unique id generated from the document's content.
     */
    documentId: string;

    /**
     * The absolute path to the file associated with this document.
     */
    filePath: string;

    /**
     * The document's content in markdown format:
     * - `string[]` if paged (one string per page).
     * - `string` otherwise (full content).
     */
    text: string | string[];
};

export type DefaultConverterConfig = Omit<DynamicConverterConfig, 'strategy'>;

export type ConverterConfig = {

    /**
     * Represents the canonical name or id of this converter.
     *
     * IMPORTANT: Using a name that is already registered by existing user-defined or built-in converter factories will overwrite those factories with this implementation.
     */
    strategy: string;

    /**
     * Additional options required by the strategy of this converter.
     */
    strategyOptions?: Options;

    /**
     * The input file format supported by this converter.
     *
     * Examples: `.pdf`, `.docx`, `.txt`
     */
    from: string;

    /**
     * The maximum size in bytes allowed for an input file.
     */
    maxFileSizeBytes: number;
};

export type Converter = {

    /**
     * Represents the converter config used to create this concrete converter.
     */
    config: ConverterConfig;

    /**
     * Converts an input document.
     *
     * @param inputDocument the input document to convert.
     * @returns the conversion result.
     */
    convert: (inputDocument: InputDocument) => Promise<ConvertedDocument>;
};

export type DynamicConverterConfig = {
    strategy: string;
    strategyOptions?: Options | ((abortSignal?: AbortSignal) => Promise<Options>);
    from: string;
    maxFileSizeBytes: number;
};

export type ConvertersConfig = {
    configs: DynamicConverterConfig[] | (() => Promise<DynamicConverterConfig[]>);
} & Version;

export type ConverterFactory = {
    /**
     * Represents the canonical name or id of this converter factory.
     *
     * IMPORTANT: Using a name that is already registered by existing user-defined or built-in converter factories, will overwrite those factories with this implementation.
     */
    strategy: string;

    /**
     * Used when no user-defined converter config exists (ex converters.[json|jsonc|js|ts] file)
     *
     * @param abortSignal a signal object that will be used to abort this operation.
     * @returns a list of default converter configs.
     */
    getDefaultConverterConfig: (abortSignal?: AbortSignal) => Promise<DefaultConverterConfig>;

    /**
     * @param config a converter config containing the converter name.
     * @param abortSignal a signal object that will be used to abort this operation.
     * @returns a converter implementation that will be used for document conversion.
     */
    getConverter: (config: ConverterConfig, abortSignal?: AbortSignal) => Promise<Converter>;
} & Version;

export type EmbeddingConfig = {
    /**
     * The maximum size of a chunk in tokens. Controls the granularity of the input data.
     * IMPORTANT: This number must be less than the (configured/inferred) maxInputSize of the embedding model.
     */
    maxChunkSize: number;

    /**
     * The number of tokens that overlap between consecutive chunks.
     * Helps preserve context across chunk boundaries.
     */
    chunkOverlap: number;

    /**
     * The embedding model used to generate embeddings for the extracted chunks.
     */
    embedder?: {

        /**
         * The provider name (must match an entry in the `models.*` configuration).
         */
        providerName: string;

        /**
         * The model name (must exist in the provider's configured models list).
         */
        modelName: string;
    };
};

export type StorageConfig = {

    /**
     * Absolute file path to the locally stored database file. Supports environment variables expension.
     */
    storagePath: string;
};

export type RAGPipelineConfig = {

    /**
     * Maps source file formats (`from`) to specific processing strategies.
     * The `strategy` value must correspond to an available **configured converter**.
     *
     * IMPORTANT: If multiple converters support the same format, the first one in the list takes precedence.
     * @see ConverterConfig
     */
    converters?: { from: string, strategy: string }[];

    /**
     * Configuration object for the embedding component of the RAG pipeline.
     */
    embeddingConfig?: EmbeddingConfig;

    /**
     * Configuration object for the storage component of the RAG pipeline.
     */
    storageConfig?: StorageConfig;
} & Version;

export type API = {
    log: {
        error: (message: string) => void;
        warning: (message: string) => void;
        info: (message: string) => void;
        debug: (message: string) => void;
    };
    runtime: {
        getEnvVar?: (name: string, abortSignal?: AbortSignal) => Promise<string | undefined>;
        getFileContents?: (path: string, abortSignal?: AbortSignal) => Promise<string | undefined>;
        getFetchModule?: () => any;
        getSetting?: (settingId: string, abortSignal?: AbortSignal) => Promise<any>;
        getRules?: () => Promise<RuleFile[]>;
        /**
         * Returns the platform the runtime is executing on.
         * @returns The platform identifier (e.g., "linux", "darwin", "win32").
         */
        getPlatform?: () => Platform;
        /**
         * Executes a shell command and returns its result.
         * @param command The shell command to execute.
         * @param options Optional execution options (cwd, env, timeout, maxOutputSize).
         * @param abortSignal Optional signal to abort the command execution.
         * @returns A promise resolving to the execution result.
         */
        exec?: (command: string, options?: ExecOptions, abortSignal?: AbortSignal) => Promise<ExecResult>;
    };
    prompt: {
        expand: (content: string, modelConfig?: ModelConfig, abortSignal?: AbortSignal) => Promise<string | undefined>;
    };
    builtin: {
        modelFactories?: ReadonlyMap<string, ModelFactory>;
        fileEditing: {
            promptInstructions: () => string;
            modelResponseProcessor: () => ((response: string) => Promise<FileEdit[]>);
            verissimo: {
                promptInstructions: () => string;
                modelResponseProcessor: () => ((response: string) => Promise<{ fileEdits: VerissimoFileEdit[], erroneousEditInfos: VerissimoFailureAutocorrectPreviousAttemptInfo[] }>);
            };
        };
    };
} & Version;

declare global {
    const acquireDvtAiApi: () => API;
}
